### ISSUE TITLE
No files issues

### ISSUE THREAD

**Issue by Lireanstar** [Wisc-HCI/Synthe#1]
../intent_parser/projects/default/{}'.format(d) for d in os.listdir('../intent_parser/projects/default/') if os.path.isdir('../intent_parser/projects/default/{}'.format(d))
there is no files ../intent_parser/projects/default/
how can i get these files?

**Comment by dporfirio** [comment]
I've added the ability to pre-train speech models prior to executing Synthé. From the intent_parser folder run ```sh create_speech_data.sh```. This information is now reflected in the readme.

**Comment by Lireanstar** [comment]
OK,thanks!
